First version application
DictGet/ecce-homo pull request #1
Opened 2016-11-16 11:24 UTC by maikthomas

2016-11-16 12:15 UTC, fmartingr commented
@maikthomas If you're going to use multiple modules you need to use a package namespace as top-level hierarchy. A `eccehomo` package maybe?

2016-11-22 12:13 UTC, fmartingr requested changes
- Create a `README.md` file with explanations and usage.
- :scroll: Docstrings missing almost everywhere.
- You have a `test_settings.filename` variable and you don't use it on the tests.

2016-11-22 12:13 UTC, fmartingr commented on eccehomo/app.py
> +def get_image(filename, **kwargs):
:scroll: Docstrings missing

2016-11-22 12:13 UTC, fmartingr commented on requirements/base.txt
> +
Two trailing newlines

2016-11-22 12:13 UTC, fmartingr commented on requirements/test.txt
> +nose==1.3.7
`-r base.txt` missing

2016-11-22 12:13 UTC, fmartingr commented on eccehomo/test_settings.py
> +TEST_MEDIA_ROOT = os.path.join(os.getcwd(), 'test_media')
I think this is better on the OS temp folder, cleaning it at the end of the tests.

2016-11-22 12:13 UTC, fmartingr commented on eccehomo/test_settings.py
> +filename = os.path.join(TEST_MEDIA_ROOT, 'test_image.jpg')
You can avoid having this file using:
- A environment variable override on the `run_tests.py` file 
- Not having this `filename` variable here, setup on the `setUpClass`/`setUp` of your tests.

2016-11-29 17:57 UTC, miguelgr reviewed
In general lacking of docstrings in the most important functions.

2016-11-29 17:57 UTC, miguelgr commented on eccehomo/utils.py
> +    except Exception as e:
A more specific exception like IOError ?

2016-11-29 17:57 UTC, miguelgr commented on eccehomo/app.py
> +    if create_image(absolute_path, resized_absolute_path, **kwargs):
Making a function to return a boolean to check if smth went OK is kindy tricky, isn't it?
![64347038](https://cloud.githubusercontent.com/assets/1484589/20721738/2aee9594-b664-11e6-854b-eaf210de0acd.jpg)

2016-11-29 17:57 UTC, miguelgr commented on eccehomo/fields.py
> +            'Default type cannot be explicity chosen. Omit t parameter.',
:memo: the parameter.

2016-11-29 17:57 UTC, miguelgr commented on eccehomo/app.py
> +import os
@maikthomas @fmartingr `import os.path` :question: 
http://stackoverflow.com/questions/2724348/should-i-use-import-os-path-or-import-os

2016-12-01 12:09 UTC, maikthomas commented on eccehomo/fields.py
> +            'Default type cannot be explicity chosen. Omit t parameter.',
`'t'` parameter e.g. `?w=100&h=50&t=cover`

2016-12-01 14:00 UTC, miguelgr commented on eccehomo/fields.py
> +            'Default type cannot be explicity chosen. Omit t parameter.',
Aaa ok. Thought it was a typo. My bad

2016-12-12 08:47 UTC, fmartingr commented on eccehomo/test_settings.py
> +TEST_MEDIA_ROOT = os.path.join(os.getcwd(), 'test_media')
Instead of using the current path for test media, I would use a folder inside of `/tmp` which is disposable.

2016-12-12 08:49 UTC, fmartingr commented on eccehomo/test_settings.py
> +filename = os.path.join(TEST_MEDIA_ROOT, 'test_image.jpg')
You can use an environment variable to retrieve this (so it can be overriden at runtime). Also this is better implemented directly in the test class instead of on a test config file.

2016-12-12 11:34 UTC, maikthomas commented on eccehomo/test_settings.py
> +filename = os.path.join(TEST_MEDIA_ROOT, 'test_image.jpg')
I have removed the settings file and create the image in the `setUpClass` for the `test_app` tests. So the `filename` variable is now contained to that file.

2016-12-12 11:34 UTC, maikthomas commented on eccehomo/test_settings.py
> +TEST_MEDIA_ROOT = os.path.join(os.getcwd(), 'test_media')
I have done this using `tempfile.mkdtemp()`

2017-03-13 17:25 UTC, fmartingr approved these changes

2017-03-13 17:25 UTC, merged